name: haveli-gan
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python and CUDA
  - python=3.10
  - cudatoolkit=12.1
  
  # PyTorch ecosystem (compatible with CUDA 12.1-13)
  - pytorch>=2.5.0
  - torchvision>=0.20.0
  - torchaudio>=2.5.0
  - pytorch-cuda=12.1
  
  # Core scientific computing
  - numpy>=1.24.0
  - scipy>=1.10.0
  
  # Image processing and computer vision
  - opencv>=4.12.0
  - scikit-image>=0.19.0
  
  # Data visualization and plotting
  - matplotlib>=3.7.0
  - seaborn>=0.11.0
  
  # GUI toolkit for interactive applications
  - tk
  
  # System libraries
  - libjpeg-turbo
  - mkl
  - mkl-service
  - blas
  
  # Package manager
  - pip
  
  # Pip-only packages
  - pip:
    # Core ML utilities
    - tqdm>=4.65.0
    
    # Image processing libraries
    - Pillow>=10.0.0
    - opencv-python>=4.12.0
    
    # Evaluation metrics and image quality assessment
    - scikit-image>=0.19.0
    - seaborn>=0.11.0
    
    # Development and debugging tools
    - argparse
    - pathlib
    - glob2
    
    # Jupyter ecosystem for development
    - jupyter>=1.0.0
    - ipython>=8.0.0
    - notebook>=6.0.0
    
    # Additional utilities
    - json5
    - pyyaml
    - requests
    
    # Optional: For advanced FID score calculations
    - scipy>=1.10.0

